modules:
  - name: dialogModule
    enabled: true
    description: Viser compliance advarsler i realtid
    path: frontend/dialog_module/

  - name: adminModule
    enabled: false
    description: Giver adgang til admin-dashboard
    path: frontend/admin_module/

  - name: loggingModule
    enabled: true
    description: Logger prompts til backend for compliance-analyse
    path: backend/logging/

  - name: riskModel
    enabled: true
    description: Risikoanalyse baseret på nøgleord
    path: backend/risk_model/

  - name: exportModule
    enabled: false
    description: Gør det muligt at eksportere data
    path: backend/export/

  - name: playgroundModule
    enabled: true
    description: Frontend træningsmiljø på Vercel
    path: frontend/playground/